SW-714 Encode image URLs
findologic/plugin-shopware-unified pull request #354
Opened 2022-04-29 09:30 UTC by TobiasGraml11

2022-04-29 12:58 UTC, dblaichinger requested changes

2022-04-29 12:58 UTC, dblaichinger commented on FinSearchUnified/Tests/Helper/StaticHelperTest.php
> +            'special characters in path are encoded' => [
image path with https

2022-04-29 12:58 UTC, dblaichinger commented on FinSearchUnified/Tests/Helper/StaticHelperTest.php
> +            'works without secure protocol' => [
image path with http

2022-04-29 12:58 UTC, dblaichinger commented on FinSearchUnified/Tests/Helper/StaticHelperTest.php
> +            'works for sub domain secure protocol' => [
image path with https and subdomain

2022-04-29 12:58 UTC, dblaichinger commented on FinSearchUnified/Tests/BusinessLogic/Models/FindologicArticleModelTest.php
> +        $imagesProperty->setAccessible(true);
Is there no getter for images? We should try to avoid reflection classes

2022-04-29 12:58 UTC, dblaichinger commented on FinSearchUnified/Tests/BusinessLogic/Models/FindologicArticleModelTest.php
> +            ->willReturn('https://via.placeholder.com/300/F00/fff/test²!Üä´°.png');
Url is used twice, could be variable `$actualImageUrl`

2022-04-29 12:58 UTC, dblaichinger commented on FinSearchUnified/Helper/StaticHelper.php
> +    }
Pretty hard to read, great that we have unit tests in place to ensure it does the right thing 👍

2022-04-29 12:59 UTC, dblaichinger commented on FinSearchUnified/Tests/Helper/StaticHelperTest.php
> +            'works without secure protocol' => [
Note: Try to describe what the provided data gives you, not what the unit test is about.

2022-05-02 06:45 UTC, TobiasGraml11 commented on FinSearchUnified/Tests/BusinessLogic/Models/FindologicArticleModelTest.php
> +        $imagesProperty->setAccessible(true);
No, there is not

2022-05-02 06:56 UTC, dblaichinger requested changes

2022-05-02 06:56 UTC, dblaichinger commented on FinSearchUnified/Tests/Helper/StaticHelperTest.php
> +            'mage path with https and subdomain' => [
```suggestion
            'image path with https and subdomain' => [
```

2022-05-02 06:56 UTC, dblaichinger commented on FinSearchUnified/Tests/BusinessLogic/Models/FindologicArticleModelTest.php
> +        $imagesProperty->setAccessible(true);
How about adding one?

2022-05-02 06:58 UTC, TobiasGraml11 commented on FinSearchUnified/Tests/BusinessLogic/Models/FindologicArticleModelTest.php
> +        $imagesProperty->setAccessible(true);
I don't think that changes to libflexport are in the scope of this story

2022-05-02 07:08 UTC, dblaichinger approved these changes

2022-05-02 07:17 UTC, merged