SW-560 Use the right dimension of product images in export
findologic/plugin-shopware-unified pull request #364
Opened 2022-06-02 11:04 UTC by nenadj-soprex

2022-06-03 11:01 UTC, TobiasGraml11 requested changes

2022-06-03 11:01 UTC, TobiasGraml11 commented on FinSearchUnified/BusinessLogic/Models/FindologicArticleModel.php
> +                    $bestExportHeight = 600;
Please add those as constants of the class

2022-06-03 11:01 UTC, TobiasGraml11 commented on FinSearchUnified/BusinessLogic/Models/FindologicArticleModel.php
> +                    $bestExportResolution = sprintf("%dx%d", $bestExportWidth, $bestExportHeight);
Please rename `best` to `preferred`

2022-06-03 11:01 UTC, TobiasGraml11 commented on FinSearchUnified/BusinessLogic/Models/FindologicArticleModel.php
> +                        $image = $thumbnails[array_key_first($thumbnailsSizes)];
```suggestion
                        foreach (array_keys($thumbnails) as $resolution) {
                            $dimensions = explode('x', $resolution);
                            $thumbnailsSizes[$resolution] = intval($dimensions[0]) * intval($dimensions[1]);
                        }
                        krsort($thumbnailsSizes, 1);
                        $image = $thumbnails[array_key_first($thumbnailsSizes)];
```

2022-06-03 11:01 UTC, TobiasGraml11 commented on FinSearchUnified/BusinessLogic/Models/FindologicArticleModel.php
> +                        krsort($thumbnailsSizes, 1);
```suggestion
                        krsort($thumbnailsSizes, SORT_NUMERIC);
```

2022-06-03 11:01 UTC, TobiasGraml11 commented on FinSearchUnified/BusinessLogic/Models/FindologicArticleModel.php
> +                    }
Move this to a separate function. This part should look something like this:
`$image = $this->getPreferredImage($thumbnails, $imageSize);`

2022-06-03 11:01 UTC, TobiasGraml11 commented on FinSearchUnified/Tests/BusinessLogic/Models/FindologicArticleModelTest.php
>      public function testCoverImageIsExportedAsFirstImage()
Please also test the new `getPreferredImage` function.
As it is now isolated in a separate function, you can just call it with the thumbnails and image size that you want to test.

2022-06-08 12:28 UTC, nenadj-soprex commented on FinSearchUnified/Helper/StaticHelper.php
> +            krsort($thumbnailsSizes, SORT_NUMERIC);
```suggestion
            ksort($thumbnailsSizes, SORT_NUMERIC);
            $index = 0;
            foreach ($thumbnailsSizes as $key => $thumbnailsSize) {
                if ($thumbnailsSize > $imageSize) {
                    $index = $key;
                    break;
                }
            }
            $image = $thumbnails[$index];
```

2022-06-08 12:33 UTC, nenadj-soprex commented on FinSearchUnified/Helper/StaticHelper.php
> +            krsort($thumbnailsSizes, SORT_NUMERIC);
@TobiasGraml11 
Now the logic use biggest thumbnails, if main image smaller then preferred or preferred not exist. If we extend logic with that, not biggest at all will be used, then the first bigger thumbnail then preferred size.
Are you approve?

2022-06-08 12:34 UTC, nenadj-soprex commented on FinSearchUnified/Tests/Helper/StaticHelperTest.php
> +            ]
```suggestion
            ],
            'Thumbnails array not have preferred size and Main Image is Smaller then preferred, use first bigger' => [
                'preferredExportWidth' => 600,
                'preferredExportHeight' => 600,
                'thumbnails' => [
                    '100x100' => 'image_100x100.jpg',
                    '300x300' => 'image_300x300.jpg',
                    '800x800' => 'image_800x800.jpg',
                    '900x900' => 'image_900x900.jpg'
                ],
                'imageSize' => 359999,
                'imageUrl' => 'image.jpg',
                'expectedImageUrl' => 'image_800x800.jpg',
            ]
```

2022-06-08 12:35 UTC, nenadj-soprex commented on FinSearchUnified/Tests/Helper/StaticHelperTest.php
> +            ]
@TobiasGraml11 if we extend our logic this test will pass to. Use first bigger then preferred.

2022-06-08 16:05 UTC, TobiasGraml11 requested changes

2022-06-08 16:05 UTC, TobiasGraml11 commented on FinSearchUnified/Tests/Helper/StaticHelperTest.php
> +            'Thumbnails array not have preferred size, but Main Image is equal then preferred' => [
```suggestion
            'Thumbnails array does not have preferred size, but main image is equal to preferred' => [
```

2022-06-08 16:05 UTC, TobiasGraml11 commented on FinSearchUnified/Tests/Helper/StaticHelperTest.php
> +            'Thumbnails array not have preferred size, but Main Image is Bigger then preferred' => [
```suggestion
            'Thumbnails array does not have preferred size, but main image is bigger than preferred' => [
```

2022-06-08 16:05 UTC, TobiasGraml11 commented on FinSearchUnified/Tests/Helper/StaticHelperTest.php
> +            'Thumbnails array not have preferred size and Main Image is Smaller then preferred' => [
```suggestion
            'Thumbnails array does not have preferred size and main image is smaller than preferred' => [
```

2022-06-08 16:05 UTC, TobiasGraml11 commented on FinSearchUnified/Tests/Helper/StaticHelperTest.php
> +            'Thumbnails array not have preferred size and Main Image is Smaller then preferred, use first bigger' => [
```suggestion
            'Thumbnails array does not have preferred size and main image is smaller than preferred, use next biggest' => [
```

2022-06-08 16:05 UTC, TobiasGraml11 commented on FinSearchUnified/Helper/StaticHelper.php
> +        return $image;
This code looks too much stuck together. And it can be a bit simplified.

```suggestion
        $preferredExportResolution = sprintf("%dx%d", $preferredExportWidth, $preferredExportHeight);

        if (array_key_exists($preferredExportResolution, $thumbnails)) {
            return $thumbnails[$preferredExportResolution];
        } elseif ($imageSize < $preferredExportWidth * $preferredExportHeight) {
            $thumbnailsSizes = [];
            foreach (array_keys($thumbnails) as $resolution) {
                $dimensions = explode('x', $resolution);
                $thumbnailsSizes[$resolution] = intval($dimensions[0]) * intval($dimensions[1]);
            }
            
            ksort($thumbnailsSizes, SORT_NUMERIC);

            foreach ($thumbnailsSizes as $key => $thumbnailsSize) {
                if ($thumbnailsSize > $imageSize) {
                    return $thumbnails[$key];
                }
            }
        }

        return $image;
```

2022-06-13 05:23 UTC, TobiasGraml11 approved these changes

2022-06-13 05:23 UTC, merged